name: CodeBench
options:
  bundleIdPrefix: com.focus.codebench
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  LeetPulseDesignSystem:
    path: ../../LeetPulseDesignSystem

targets:
  CodeBench:
    type: application
    platform: iOS
    sources:
      - CodeBench
    dependencies:
      - package: LeetPulseDesignSystem
        product: LeetPulseDesignSystemCore
    resources:
      - path: CodeBench/Resources
        type: folder
      - path: CodeBench/Assets.xcassets
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_STRICT_CONCURRENCY: complete
        PRODUCT_BUNDLE_IDENTIFIER: com.focus.codebench
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_STYLE: Automatic
